name: Build and deploy Python app to Azure Web App - pruebahackathon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: /tmp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pruebahackathon'  # Nombre de tu App Service en Azure
          slot-name: 'Production'       # Nombre del slot de despliegue (opcional)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BB615DAA3C1844E087A }}  # Debes configurar esto en los secretos de tu repositorio
